### PR TITLE
Papadopoulos/matrix free mat zero rows columns

### PR DESCRIPTION
**Pull request by ioannisPApapadopoulos**
First pass at implementing a matrix free `duplicate` and `matZeroRowsColumns`

### CODE REVIEW

**Comment by ioannisPApapadopoulos** [comment]
@pefarrell

**Comment by pefarrell** [comment]
I'd probably prepare two pull requests. Do the `duplicate` one first, since it's more straightforward.

**Comment by pefarrell** [comment]
It would make your case stronger if you had PETSc solver configurations that failed without these new methods, but run with them.

**Comment by pefarrell** [comment]
You could add these as tests in `test/regression/test_XXX.py`.

**Comment by pefarrell** [comment]
Perhaps an obstacle problem with SNESVINEWTONRSLS and matfree?

**Comment by ioannisPApapadopoulos** [comment]
Thanks! I will split them up. A SNESVINEWTONRSLS obstacle example would be tricky because it would also require my version of virs.c. The current virs.c in firedrake's petsc branch is using `MatCreateSubMatrix` rather than `MatZeroRowsColumns`

**Pull request closed without merging**
